postgres: support/db/start.sh
api: target/debug/bldr-api start --path /tmp/depot --config /home/salim/Workspace/habitat/config/config_api.toml
admin: target/debug/bldr-admin start
router: target/debug/bldr-router start
jobsrv: target/debug/bldr-job-srv start
scheduler: target/debug/bldr-scheduler start
sessionsrv: target/debug/bldr-session-srv start --config /home/salim/Workspace/habitat/config/config_sessionsrv.toml
originsrv: target/debug/bldr-origin-srv start
worker: target/debug/bldr-worker start --config /home/salim/Workspace/habitat/config/config_worker.toml
worker: target/debug/bldr-worker start --config /home/salim/Workspace/habitat/config/config_worker.toml
